from pathlib import Path


class RepositoryStructure:
    """
    Responsible for creating the repository folder structure.
    """

    def __init__(self, root: str = "leetcode-solutions"):
        self.root = Path(root)

    def create_repository(self):
        """
        Create the main repository folder.
        """
        self.root.mkdir(exist_ok=True)

    def create_difficulty_folders(self):
        """
        Create Easy, Medium and Hard folders.
        """
        difficulties = [
            "Easy",
            "Medium",
            "Hard"
        ]

        for difficulty in difficulties:
            (self.root / difficulty).mkdir(exist_ok=True)

    def create_root_readme(self):
        """
        Create README.md if it does not already exist.
        """
        readme = self.root / "README.md"

        if not readme.exists():
            readme.write_text(
                "# LeetCode Solutions\n\n"
                "This repository is automatically generated by LeetSync.\n",
                encoding="utf-8"
            )

    def initialize(self):
        """
        Initialize the repository structure.
        """
        self.create_repository()
        self.create_difficulty_folders()
        self.create_root_readme()


if __name__ == "__main__":
    repository = RepositoryStructure()
    repository.initialize()

    print("Repository structure created successfully.")