from pathlib import Path


class ReadmeGenerator:
    """
    Generates the repository README file.
    """

    def __init__(self, root: str = "leetcode-solutions"):
        self.root = Path(root)

    def generate(
        self,
        total: int,
        easy: int,
        medium: int,
        hard: int,
        recent_problem: str,
    ):

        content = f"""# 🚀 LeetCode Solutions

Automatically generated by LeetSync.

---

## Statistics

- Total Solved : {total}
- Easy : {easy}
- Medium : {medium}
- Hard : {hard}

---

## Latest Solved Problem

- {recent_problem}

---

Generated using ❤️ LeetSync
"""

        readme = self.root / "README.md"

        readme.write_text(content, encoding="utf-8")


if __name__ == "__main__":

    generator = ReadmeGenerator()

    generator.generate(
        total=1,
        easy=1,
        medium=0,
        hard=0,
        recent_problem="Two Sum",
    )

    print("README generated successfully.")